src/components/common/Input/Input.style.ts, src/components/common/Input/Input.tsx, src/components/common/Input/Input.type.ts, src/components/common/Input/index.ts, src/styles/theme.ts
공통 컴포넌트인 Input 컴포넌트를 구현했습니다.
```typescript
<Input
width={'20rem'}
fontSize={2}
margin={1.5}
label={'라벨이다'}
placeholder={'닉네임 써라'}
errorMessage={'에러다'}
{...props} // 추가 props들
/>
```
- `Input` 컴포넌트에서 필수 props는 `width`입니다.
- `width`는 string 타입이며, px, rem, %를 다 받을수 있도록 구현했습니다.
- `Input` 컴포넌트에서 선택 props는 `fontSize`, `margin`, `label`, `placeholder`, `errorMessage` 입니다.
- `fontSize`는 number 타입이며, 라벨, input, 에러 메시지의 폰트 사이즈를 의미합니다. 생략 시 기본 값으로 `2`가 설정됩니다. (단위는 rem)
- `margin`은 number 타입이며, 라벨, input, 에러 메시지 간 간격을 의미합니다. 생략 시 기본 값으로 `1.5`가 설정 됩니다. (단위는 rem)
- `label`은 string 타입이며, input 위에 붙는 라벨 역할을 합니다.
- `placrholder`는 string 타입이며, input의 placeholder 역할을 합니다.
- `errorMessage`는 string 타입이며, input 하단 에러 메시지 역할을 합니다.
- `styles > theme.ts` 파일에 `error_red` 색상을 추가하였습니다. 라이트 모드일 때는 `#F82B2B` 이며, 다크 …
=> [#29] Input 컴포넌트 구현 v1.0.0

src/components/common/Badge/Badge.style.ts, src/components/common/Badge/Badge.tsx, src/components/common/Badge/Badge.type.ts, src/styles/theme.ts
기존의 Badge 컴포넌트를 확장하였습니다.
위 사진 코드
```js
<Badge
$margin="10px 0px 3px 10px"
$size={'xxs'}
$state="basic"
$text="프론트엔드"
/>
<Badge
$size={'xs'}
$state="basic"
$text="프론트엔드"
/>
<Badge
$size={'s'}
$state="basic"
$text="프론트엔드"
/>
<Badge
$size={'m'}
$state="basic"
$text="프론트엔드"
/>
<Badge
$size={'m'}
$state="hot"
$text="HOT"
/>
```
- 갤럭시 폴드 UI에 필요한 xss, xs 사이즈를 만들었습니다.
- Tagfilter에서 margin값이 쓰이므로 `margin`을 받는 props를 추가하였습니다.
- 이제 뱃지 컴포넌트가 fix 되어있기에 HOT 태그도 필요하여 추가하였습니다.
=> [#52] Badge 컴포넌트 구현 v1.1.0

src/components/common/Textarea/Textarea.style.ts, src/components/common/Textarea/Textarea.tsx, src/components/common/Textarea/Textarea.type.ts, src/components/common/Textarea/index.ts
공통 컴포넌트인 Textarea 컴포넌트를 구현했습니다.
- dev 브랜치 내용이 pull 되지 않아서 테마 적용을 못했습니다 ㅠㅠ Input 컴포넌트와 다른 부분은 `input이냐 textarea이냐` 차이 일 뿐이라 [Input 컴포넌트](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/pull/45) 스크린샷과 큰 차이는 없습니다 !
```typescript
<Textarea
width={'50rem'}
height={'50rem'}
fontSize={2}
margin={1.5}
label={'라벨이다'}
placeholder={'닉네임 써라'}
errorMessage={'에러다'}
/>
```
- `Textarea` 컴포넌트에서 필수 props는 `width`, `height`입니다.
- `width`는 string 타입이며, px, rem, %를 다 받을수 있도록 구현했습니다.
- `height`는 string 타입이며, px, rem, %를 다 받을수 있도록 구현했습니다.
- `Textarea` 컴포넌트에서 선택 props는 `fontSize`, `margin`, `label`, `placeholder`, `errorMessage` 입니다.
- `fontSize`는 number 타입이며, 라벨, input, 에러 메시지의 폰트 사이즈를 의미합니다. 생략 시 기본 값으로 `2`가 설정됩니다. (단위는 rem)
- `margin`은 number 타입이며, 라벨, textarea, 에러 메시지 간 간격을 의미합니다. 생략 시 기본 값으로 `1.5`가 설정 …
=> [#30] Textarea 컴포넌트 구현 v1.0.0

src/components/common/Input/Input.style.ts, src/components/common/Input/Input.tsx
- 모바일 환경일 때 Input 컴포넌트의 라벨과 input의 폰트 사이즈를 -0.2rem 보정했습니다.
- label props를 넘겨주지 않았을 때 <label> 태그가 남아있는 문제를 해결했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/fbc28427-2051-408c-b54e-530f65dafc94
위 스크린샷은 화면 너비가 줄어들 때 font-size가 바뀌는 것을 녹화한 것입니다.
- 에러 메시지는 너무 작아져서 따로 보정하진 않았습니다. 에러 메시지도 보정 해줘야 할까요 ?
=> [#58] Input 컴포넌트 v1.0.1

src/components/common/Button/Button.style.ts, src/components/common/Button/Button.tsx, src/components/common/Button/Button.type.ts, src/components/common/Button/index.ts
- 프로젝트 내에서 범용적으로 사용될 사각형 버튼 컴포넌트를 구현했습니다.
- width, height는 string으로 받기 때문에 다양한 단위 커스텀이 가능합니다.
- 이 외에도 background-color, text-color, hover관련 color 등 다양한 props가 존재하고, 확장된 props를 이용해 커스텀 가능합니다.
- 위 예시 사진에서 2번째 버튼이 커스텀 없는 default 버튼 형태입니다.
> 예시 코드
```jsx
<Button
width="40rem"
height="4rem"
backgroundColor={theme.background_color}
textColor={theme.symbol_color}
borderColor={theme.symbol_color}
hoverBackgroundColor={theme.symbol_color}
hoverTextColor={theme.background_color}
textSize="1.6rem"
onClick={handleClick}
>
+ 새 질문 추가하기
</Button>
```
- 버튼을 커스텀할 수 있습니다.
- 모바일 환경일 경우 글씨 크기를 -0.3rem 자동 보정해주었습니다.
- 클릭 시 파란 박스가 나타나는 현상을 제거하고 `hoverBackgroundColor` 색상을 넣었습니다.
버튼의 **비활성화/활성화** 기능을 사용하시려면 `isActive`, `disabled` 속성을 **동시에 사용해야 UI에 어색함이 없습니다.**
> 예시 코드
```jsx
const [isActive, setIsActive] = …
```
=> [#38] Button(사각형) 컴포넌트 구현 v1.0.0

src/components/common/CircleButton/CircleButton.style.ts, src/components/common/CircleButton/CircleButton.tsx, src/components/common/CircleButton/CircleButton.type.ts, src/components/common/CircleButton/index.ts
- 질문 및 질문 꾸러미 추가 동작을 수행하는 원형 버튼입니다.
- 사각형 버튼과 달리 사용되는 곳이 제한적이기 때문에 `size`, `isBackgroundWhite` 2개로 props를 대폭 줄였습니다.
- 이렇게 버튼이 올라갈 컴포넌트의 배경 색이 버튼 색과 같은 경우, `isBackgroundWhite=true` 로 설정해야 합니다.
> 예시 코드
```jsx
<ShadowBox isActive> // 배경이 green인 박스 컨테이너
<span>어쩌고저쩌고질문이어쩌고</span>
<CircleButton isBackgroundWhite /> // 배경이 버튼 내부 색상과 같은 green이므로 isBackgroundWhite=true 설정
</ShadowBox>
```
- ShadowBox의 오른쪽에 질문 추가 버튼을 위치시키려면 다음과 같이 코드를 작성합니다.
> 예시 코드
```jsx
<ShadowBox
...
style={{ position: 'relative' }} // 부모의 position을 relative로 설정
>
<CircleButton
size="6rem"
style={{
position: 'absolute',
right: '-3rem', // - size/2
top: 'calc(50% - 3rem)', // 50% - size/2 
}}
/>
</ShadowBox>
```
- props는 일단 저렇게 2개만 열어뒀는데 더 열어주면 좋을만한 것들이 있을까요?
- 이 외에 개선할만한 부분 있다면 말씀해주세요!!!
=> [#39] Button(원형) 컴포넌트 구현 v1.0.0

src/components/common/ModalLayout/ModalLayout.style.ts, src/components/common/ModalLayout/ModalLayout.tsx, src/components/common/ModalLayout/index.ts, src/hooks/useModal.tsx, src/hooks/useResize.tsx, src/routes/index.tsx, src/stores/index.ts, src/utils/bodyScrollLock.ts, src/utils/isMobile.ts
우선 사과의 말씀 드립니다,,, 생각보다 모달을 구현하다보니 해야할 게 정말 많아서 같이 구현하였습니다. 
또한 선언한 기간보다 기간이 길어졌는데, 더 열심히 해보겠습니다.
[kiwing_modal_v1.0.0.webm](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/f55de2fd-f2b3-4d19-8c4e-722f95fbc977)
[kiwing_modal_mobile_v1.0.0.webm](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/1e10f892-64fa-4ea5-8380-2fae5877f2c4)
store/index.ts에 modalStore와 관련 타입을 export 형태로 선언하였습니다.
전역 상태는 isOpen, title, content, callBack의 `단일 상태`만을 가집니다. 이러한 특성으로 인해서 모달은 항상 단일 개체만 생성이 가능합니다. 물론 모달을 생성 후 다른 모달로 이동은 가능하지만, 추천드리지는 않습니다.
```ts
export interface ModalType {
title: string;
content: React.ReactNode;
callBack?: () => void;
}
export interface ModalState extends ModalType {
isOpen: boolean;
openModal: (modalData: ModalType) => void;
closeModal: () => void;
} …
```
=> [#42] 전역 상태 모달 v1.0.0

src/components/common/Badge/Badge.style.ts, src/components/common/Badge/Badge.tsx, src/components/common/Badge/Badge.type.ts, src/styles/theme.ts
공통 컴포넌트인 뱃지컴포넌트에 스크랩숫자를 나타내는 뱃지스타일을 추가했습니다.
- 1000개 미만은 숫자로 보이게 해두었고 그 이상부터는 K+를 붙이도록 구현해두었습니다.
- 기존의 `$text` props는 `string` 타입이였는데 이번에 `ReactNode`으로 변경하였습니다.
- 전역 테마에 스크랩 뱃지 색상을 추가했습니다.
```js
subscribed_background_color: '#FFE500',
subscribed_color: '#E3A400',
```
```js
import Badge from '@/components/common/Badge';
return (
<>
<Badge
$size={'xs'}
$state="subscribedTag"
$subscribedCount={2852}
/>
<Badge
$size={'xs'}
$state="subscribedTag"
$subscribedCount={1}
/>
<Badge
$size={'xs'}
$state="subscribedTag"
$subscribedCount={45}
/>
<Badge
style={{ padding: '0.5rem 1.3rem', fontSize: '1.1rem' }}
$size={'xs'}
$state="subscribedTag"
$subscribedCount={1200}
/>
<Badge
$size={'s'}
$state="subscribedTag"
$subscribedCount={990}
/>
<Badge
$size={'xs'}
$state="subscribedTag" …
```
=> [#63] Badge 컴포넌트 구현 v1.2.0

src/components/common/SearchBar/SearchBar.style.ts, src/components/common/SearchBar/SearchBar.tsx, src/components/common/SearchBar/SearchBar.type.ts, src/components/common/SearchBar/index.ts
검색바 컴포넌트를 구현했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/174ebb7d-b029-4067-aa38-572ebbf82a16
```typescript
import { useForm } from 'react-hook-form';
import SearchBar from '@/components/common/SearchBar';
const { handleSubmit } = useForm();
const onSubmit = () => {
alert('sumbit!');
};
return (
<>
<SearchBar
handleSearchIcon={() => alert('검색됨!')}
handleFormSubmit={handleSubmit(onSubmit)}
maxWidth={'500px'}
/>
</>
);
};
export default TestPage;
```
위 예시는 TestPage에서 `react-hook-form`을 사용할 때 `handleSubmit` 이용을 확인하기 위해 작성한 코드입니다.
사용하실 때 `react-hook-form`의 `register` 등과 같은 요소는 SearchBar 컴포넌트에서 `{...props}`로 받습니다 !
`react-hook-form` 사용성을 고려할 때 [참고한 자료](https://tech.osci.kr/introduce-react-hook-form/)입니다.
- `hendleSearchIcon` : 검색 아이콘에 할당 할 …
=> [#57] 검색바 컴포넌트 구현 v1.0.0

src/components/common/UserInfoCard/UserInfoCard.style.ts, src/components/common/UserInfoCard/UserInfoCard.tsx, src/components/common/UserInfoCard/UserInfoCard.type.ts, src/components/common/UserInfoCard/index.ts
- 유저 프로필 역할을 하는 UserInfoCard 컴포넌트를 구현했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/9a3c2649-aace-4b23-844d-a84cea8a224e
다크모드는 용량 문제 로 인해 아래 사진으로 대체합니다 !!
```json
[
{
"message": "string",
"data": {
"id": 0,
"nickname": "JaehyunGround",
"profileImage": "123123123123123",
"email": "gothddlek2603@gmail.com",
"tags": ["프론트엔드", "디자인", "백엔드"],
"links": [
"https://github.com/Team-kiwing",
"https://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/postshttps://velog.io/@jaehyun_ground/posts",
"https://github.com/JaeHyunGround"
], …
```
=> [#28] UserInfoCard 컴포넌트 구현 v1.0.0

src/components/SharedBundleCard/SharedBundleCard.style.ts, src/components/SharedBundleCard/SharedBundleCard.tsx, src/components/SharedBundleCard/SharedBundleCard.type.ts, src/components/SharedBundleCard/index.ts
공유된 질문꾸러미 Card 컴포넌트입니다. 
한가지의 `bundleName` props를 가지며 필수 prop이고 `string`타입입니다.
- 다크모드일때의 글씨나 아이콘의 색깔을 정하지 않은 느낌이라 어떻게 하는게 좋을까요?
- 사이즈가 줄어들때 768이하일때도 UI가 바뀌어야할까요 아님 모바일일때만 바뀌면될까요?
빠진 부분있으면 말해주세요 피드백 환영입니다! 
```js
<SharedBundleCard bundleName={'데브코스 면접 리스트'} />
```
=>  [#83] SharedBundleCard 컴포넌트 구현 v1.0.0

src/components/BundleDropDown/BundleDropDown.style.ts, src/components/BundleDropDown/BundleDropDown.tsx, src/components/BundleDropDown/BundleDropDown.type.ts, src/components/BundleDropDown/index.ts, src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.style.ts, src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.tsx, src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.type.ts, src/components/SharedBundlePage/SharedBundleDropDown/index.ts, src/utils/copyClip.ts
공유된 질문꾸러미에 필요한 드롭다운 컴포넌트입니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/81172451/2f512979-b191-415c-a648-eb401e1e7404
-  네가지의 props를 받습니다.
- `isDropDownShow` : 필수이며 BundleDropDown가 보여지는 유무를 나타내는 상태값입니다.
- `setIsDropDownShow` 필수이며 isDropDownShow 상태값을 set하는 함수입니다.
- `triggerId`: 필수이며 드롭다운 컴포넌트가 isShow=true가 되도록 해주는 HTMLElement의 id입니다.
- `width`: 선택이며  width값으로 DropDown의 크기를 설정합니다. string 타입이며 기본값으로 12rem이 들어갑니다.  컨텐츠에 오른쪽아래 배치를 하기위해서 style에 `position: absolute` 주고 `top:0`을주고 드롭다운 너비를 제외하고 오른쪽 배치를 하기위해서 `right: width` 값만큼 주었습니다.
- 복사 아이콘 클릭시 현재 URL이 복사됩니다.  참고한 코드[참고](https://w3c.github.io/clipboard-apis/#dom-clipboard-writetext)
- 현주님의 드롭다운 컴포넌트를 사용했는데 잘 사용했는지가 궁금합니다. ! !
```js
import { useState } from 'react';
import BundleDropDown from '@/components/BundleDropDown';
import …
```
=> [#89] SharedBundleDropDown 컴포넌트 구현 v1.0.0

src/components/SharedBundleCard/SharedBundleCard.style.ts, src/components/SharedBundleCard/SharedBundleCard.tsx
다크모드일 때의 SharedBundleCard의 색상을 라이트모드와 동일하게 수정하였습니다.
간단한 색상 변경입니다 !
깜빡하고 전에 1.0.0에 푸쉬를 못하고 머지하여서 ㅠㅠ 다시 수정한 내용 올립니다. !
=> [#112] SharedBundleCard 색상 변경 v1.0.1

src/components/common/Textarea/Textarea.tsx
Textarea 컴포넌트를 사용하는 곳에서 react-hook-form을 사용할 때 register 함수가 Textarea 컴포넌트 내 textarea 태그를 찾지 못하는 버그가 발생하여 textarea 태그에 ref를 추가했습니다.
`forwardRef` 를 추가한 후, textarea에 ref를 달아준 것이라 바뀐 코드는 많지 않습니다 !
=> [#131] Textarea 컴포넌트 v1.1.0

src/components/common/Input/Input.tsx
Input 컴포넌트를 사용하는 곳에서 react-hook-form을 사용할 때 register 함수가 Input 컴포넌트 내 input 태그를 찾지 못하는 버그가 발생하여 input 태그에 ref를 추가했습니다.
=> [#132] Input 컴포넌트 v1.1.1

src/components/common/Selector/Selector.style.ts, src/components/common/Selector/Selector.tsx, src/components/common/Selector/Selector.type.ts
selector 컴포넌트 사용시 토글되는 버그를 수정하였고  동일한 content 클릭시 이벤트를 막았습니다.
간단한 내용입니다. state값을 !state 방식을 true, false로 변경하였고 방어코드로 이벤트를 막아주었습니다.
=> [#155] Selector 컴포넌트 v1.2.0

vite.config.ts
개발환경에서 API 호출을 위한 프록시 서버를 설정하였습니다.
테스트 코드
```tsx
import { useEffect, useState } from 'react';
interface tagProps {
id: number;
content: string;
}
const [tags, setTags] = useState([]);
useEffect(() => {
if (tags.length === 0) {
fetch('/api/v1/tags')
.then((res) => res.json())
.then((resp) => setTags(resp.data));
}
});
// 요기다가 하시면 됩니다
console.log(tags);
return (
<>
<div>테스트 페이지 입니다.</div>
{tags.length === 0 ? (
<div>Loading</div>
) : (
<>
{tags.map((val: tagProps) => {
return (
<div key={val.id}>
<span>
{val.id} {val.content}
</span>
</div>
);
})}
</>
)}
</>
);
};
export default TestPage;
```
약간 세팅하면서 이해가 안갔던게 `/api 라는 문자열이 target 에 지정한 문자열 https://api-dev.kiwing.kr/ 로 변환되어 사용된다.` 는 문구가 있더라고요.
제가 이해하기로는 fetch('/api/v1/tags')가 …
=> [#151] 프로젝트 세팅 v1.2.0

src/components/common/Input/Input.style.ts, src/components/common/Input/Input.tsx, src/components/common/Input/Input.type.ts, src/styles/globalStyles.ts
Input 컴포넌트에 border 옵션을 줄 수 있도록 수정했습니다.
- `isOnlyBorderBottom` props를 사용하며, 
true일 때는 Input 컴포넌트의 border가 아래만 나타나고, false일 때는 사방면 border가 적용 됩니다.
```typescript
import Input from '@/components/common/Input';
return (
<>
<Input
width={'200px'}
isOnlyBorderBottom={false}
/>
{/* 사방면 border */}
<Input
width={'200px'}
isOnlyBorderBottom={true}
/>
{/* 아래만 border */}
</>
);
};
export default TestPage;
```
- globalStyle.ts 파일을 수정했습니다.
- 저번 이슈 사항이었던 `IOS 환경에서 border-bottom이 둥글게 나오는 문제` 를 해결하기 위해 추가했던 코드를 수정했는데, 모바일 환경에서 문제 없는지 한 번씩만 테스트 부탁 드립니다 !! 제가 했을 땐 문제가 없었는데 다른 팀원분들 환경에서는 어떻게 될지 모르겠어서 부탁 드립니다 ㅠㅠ
해당 PR이 머지 되는대로 SearchBar 컴포넌트에 적용하여 SearchBar v2.0.0 PR 올릴 예정입니다 !
=> [#152] Input 컴포넌트 v1.2.1

src/components/Layout/Layout.tsx, src/components/common/EasterEgg/EasterEgg.style.ts, src/components/common/Navigator/WebNavBar/WebNavBar.style.tsx, src/constants/index.ts, src/pages/NotFoundPage/NotFound.style.ts, src/styles/globalStyles.ts
전역 레이아웃 속성을 변경하였습니다.
또한 연관된 일부 간단한 속성을 변경하였습니다.
기존에는 웹에서 따로 속성을 부여하지 않고 자동적으로 스크롤 하게 했었다면
변경 값에서는 상단 내비게이션 바 만큼 padding값을 주어 떨어트려두었습니다.
또한 상단 내비게이션 바는 스크롤이 동작해도 항상 제자리에 유지됩니다.
[kiwing_layout_1.1.0.webm](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/08b74513-d640-4675-8dba-585171169659)
- 자잘자잘한 일부 변경사항이 있는데 변경된 레이아웃에 맞춘 코드입니다.
- 내비게이터의 z-index값이 많이 올랐습니다. 2 -> 9
- 페이지에서 사용하실때, 일반적인 전체 스크롤의 경우 그냥 height 100%로 래핑해주시면 됩니다!
=> [#167] 전역 레이아웃 수정 v1.1.0

src/components/common/Input/Input.style.ts, src/components/common/Input/Input.tsx, src/components/common/Input/Input.type.ts
Input 컴포넌트에 `isDisabled` props를 추가했습니다.
- `isDiabled` props는 input의 disabled 설정을 제어할 수 있는 props입니다.
- input이 disabled 되면 사용자에게 시각적으로 알려주기 위해 글자 색을 gray_400으로 설정했습니다.
브랜치 명이 잘못된 것을 이제 봤네요....ㅠㅠ 주의하겠습니다...!!
- 위에가 disabled 된 input이고 밑에는 disabled가 적용 안됐고 placeholder가 출력된 것입니다 !
<details>
<summary>Test</summary>
<div markdown="1">       
```typescript
import { useForm } from 'react-hook-form';
import Input from '@/components/common/Input';
interface InputTypes {
title: string;
content: string;
}
const { register } = useForm<InputTypes>({
defaultValues: {
title: '제목의 기본값을 뭐로 할까',
content: '그러게',
},
});
return (
<>
<Input
width={'500px'}
placeholder="이메일을 입력하세요"
isDisabled={true}
{...register('title')}
/>
<Input
width={'500px'}
placeholder="이메일을 입력하세요."
/>
</>
);
}; …
```
=> [#170] 공통 - Input 컴포넌트 v1.3.1

index.html, src/styles/globalStyles.ts
모바일 환경에서 스크롤바가 영역을 차지하는 이슈를 해결하였습니다.
모바일 환경에서 스크롤 바의 기본값은 overlay형태로 기본 영역을 차지하지 않습니다.
대표적인 삼성 갤럭시와 아이폰 사파리도 동일한 방식으로 구현됩니다.
하지만 전역에 있던 아래 코드가 임의로 스크롤바의 영역을 생성했고
그래서 모바일 환경에서의 문제점이 발생하였습니다.
```tsx
* {
&::-webkit-scrollbar {
width: 0.4rem;
}
&::-webkit-scrollbar-thumb {
background-color: ${(props) => props.theme.border_color};
border-radius: 100px;
}
}   
```
여러 해결책을 시도해 봤으나, 가장 마음에 드는 방식은 아래와 같이 
모바일 범위를 벗어날 경우에만 스크롤 바를 커스텀으로 부여하는 것이였습니다.
```tsx
@media not all and (max-width: ${MOBILE}px) {
* {
&::-webkit-scrollbar {
width: 0.4rem;
}
&::-webkit-scrollbar-thumb {
background-color: ${(props) => props.theme.border_color};
border-radius: 100px;
}
}
}
```
이때의 단점은 웹에서 화면을 줄일 경우 클래식 스크롤바가 그대로 출력된다는 것인데,
어차피 웹에서 작은 화면을 볼 일은 없을 것으로 추측하여 문제가 없을 것이라고 판단하였습니다.
이외에도 스크롤바를 아예 none으로 주는 방식도 있었는데
아예 보이지 …
=> [#194] 프로젝트 세팅(전역 스타일에 조건문 추가) v1.2.1

src/components/SharedBundle/SharedBundleCard/SharedBundleCard.const.ts, src/components/SharedBundle/SharedBundleCard/SharedBundleCard.style.ts, src/components/SharedBundle/SharedBundleCard/SharedBundleCard.tsx, src/components/SharedBundle/SharedBundleCard/SharedBundleCard.type.ts
sharedBundleDropDown 버전이 바뀌면서 코드수정을 하였습니다.
추후에 바뀐 sharedBundleDropDown도 수정해서 올리겠습니다.
- 꾸러미의 id값을 받는 props를 추가했습니다. 타입은 `number`타입입니다.
- toast 훅을 이용하여 `alert`를 대신했습니다.
=> [#203] SharedBundleCard 컴포넌트 구현 v1.1.1

src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.style.ts, src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.tsx, src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.type.ts, src/utils/copyClip.ts
DropDown의 버전이 올라가면서 자연스럽게 sharedBundleDropDown도 버전이 업데이트되었습니다.
달라진거는 많지않고 props가 조금 달라졌습니다.
- `bundleId` 필수) 꾸러미의 고유한 id값입니다. number타입입니다.
- `isShow` 필수) SharedBundleDropDown가 보여지는 유무를 나타내는 상태값입니다.
- `setIsShow` 필수) isShow 상태값을 set하는 함수입니다.
- `closeDropDown` 필수) 드롭다운의 닫히는 함수를 받습니다.
- `direction` 필수) 드롭다운이 위치할 위치를 받습니다.
- `onAddBundle` 필수) 꾸러미를 추가할 때 호출되는 함수입니다.
```js
import Button from '@/components/common/Button';
import SharedBundleDropDown from '@/components/SharedBundle/SharedBundleDropDown';
import useDropDown from '@/hooks/useDropDown';
// 요기다가 하시면 됩니다
const { triggerId, isShow, setIsShow, toggleDropDown, closeDropDown } =
useDropDown('trigger-button');
const handleClick = (e: React.MouseEvent) => {
toggleDropDown(e);
};
return (
<>
<Button …
```
=> [#209] SharedBundleDropdown 구현 v1.1.0

src/components/MyBundle/MyBundleMenu/MyBundleMenu.style.ts, src/components/MyBundle/MyBundleMenu/MyBundleMenu.tsx, src/components/MyBundle/MyBundleMenu/MyBundleMenu.type.ts, src/components/MyBundle/MyBundleMenu/index.ts
내 질문 관리 페이지 오른쪽 상단에 위치한 MyBundleMenu를 구현했습니다.
UI 위주로 작업했습니다.
MyBundleDropdown과 로직이 거의 일치하여 추후에 api 연동 작업 후 공통된 부분을 따로 빼는 작업을 진행할 예정입니다.
- UI 위주에 MyBundleDropDown과 유사하여 큰 내용은 없습니다!
=> [#200] MyBundleMenu v1.0.0

src/components/common/TagFilter/TagFilter.style.tsx, src/components/common/TagFilter/TagFilter.tsx, src/components/common/TagFilter/TagFilter.type.ts
TagFilter 컴포넌트에 isLimit props를 추가했습니다.
`isLimit` - 선택하는 태그를 3개만 선택할수있도록 제한하는 옵션입니다. boolean값이고 default는 false입니다.
- 3개를 넘어서 4개를 클릭하는 순간 경고메세지가 뜨고 4번째로 누른 태그는 다시  안눌린상태로 돌아갑니다.
- 그리고 필터에 있는 태그를 여러번 클릭하면  파란박스가 생기는것을   `user-select: none`로 막아주었습니다.
- 지금 구현하시면서 요게 필요하면 풀 땡기고 사용하시면 될거같습니다 !
=> [#196] TagFilter 컴포넌트 구현 v1.2.1

src/components/common/SearchBar/SearchBar.tsx
SearchBar 컴포넌트 사용 시, submit 할 때 실행되는 함수에 `디바운스`를 적용했습니다.
- 검색 바에 검색어 입력 후 엔터를 꾹 누르면 submit 이벤트가 여러 번 발생하여 함수가 여러 번 실행되는 문제가 있었습니다.
이는 서버의 과부화를 일으킬 수 있기에 디바운스를 걸어주어 문제를 해결할 수 있었습니다.
<details>
<summary>Test</summary>
<div markdown="1">       
```typescript
import { FormProvider, useForm } from 'react-hook-form';
import SearchBar from '@/components/common/SearchBar';
const methods = useForm({ mode: 'onBlur' });
const REGISTER = 'bundleSearch';
const bundleValidate = {
minLength: {
value: 2,
message: '최소 2글자 이상 입력해주세요',
},
};
const onSubmit = () => {
// 검색 시 실행할 함수를 입력합니다.
console.log(methods.getValues(REGISTER));
};
return (
<>
<FormProvider {...methods}>
<SearchBar
// fontSize={2}
handleSearchSubmit={onSubmit}
maxWidth={'500px'}
REGISTER={REGISTER} …
```
=> [#185] 공통 - SearchBar v2.1.0

src/apis/axiosInstance.ts
401에러가 아닌 400에러가 오는 경우 로그아웃 처리가 정상적으로 이루어지지 않고 있습니다.
에러 메세지가 구분을 못해서 그런 것 같은데, 일단 재로그인 반영하는 로직을 한 번 더 살펴봐야 할 것 같고
그전에 일단 모든 에러 케이스에서 로그아웃을 시키는 동작이 옳다고 판단되어 일단 핫픽스 요소로 올립니다 😢 
일단 요 부분 간단하게 머지해두고 다들 배포 끝나시면 같이 확인해봐요..!
=> [#239] API 토큰 로직 관련 hotfix

src/pages/SharedPage/Shared.const.ts, src/pages/SharedPage/Shared.hook.ts, src/pages/SharedPage/Shared.style.ts, src/pages/SharedPage/Shared.tsx
공유된 페이지를 구현하였습니다.
- 다음 페이지 더 불러오기를 추가하였습니다.
- 꾸러미의 제목이 아이템 높이에 맞게 높이를 지정하였습니다.
- 1.1.0 버전의 훅을 수정하였습니다. (더 불러오기를 위해서 `useQuery` => `useInfiniteQuery` 변경)
=> [#250] 공유된 꾸러미 페이지 구현 v1.2.0

src/pages/SharedItemPage/SharedItem.style.ts, src/pages/SharedItemPage/SharedItem.tsx, src/pages/SharedPage/Shared.style.ts
직접들어가서 확인하시는게 더 좋을거 같긴하지만 사진 남겨요!
##
- `max-width`: 1200px로 고정하였습니다.
- 컨텐츠의 `width` 영역을 웹에선 80%, 모바일에선 90%로 지정하였습니다.
- `navBar`와의 간격을 웹에서 3rem, 모바일에서 2rem으로 지정하였습니다.
@SoJuSo 태그필터와의 검색바와의 간격이 좀 더 있었으면해서 태그필터에서 `margin-bottom: 5rem` 정도를 주었습니다.
허브페이지에서도 통일하면 좋을거같아서 의견 맞춰봅시다 !
=> [#266] 꾸러미, 꾸러미 상세 페이지 레이아웃 수정

src/components/common/SearchBar/SearchBar.tsx, src/components/common/SearchBar/SearchBar.type.ts, src/components/common/UserInfoCard/UserInfoCard.style.ts, src/components/common/UserInfoCard/UserInfoCard.tsx, src/pages/AuthPage/Auth.style.ts, src/pages/MainPage/Main.style.ts, src/pages/RegisterPage/Register.style.ts
메인, 로그인, 회원가입 페이지의 레이아웃을 합의된 사항으로 수정했습니다.
UserInfoCard, SearchBar 컴포넌트의 수정사항을 반영했습니다.
- 로그인, 회원가입 페이지에서는 위, 아래 네브바가 제거되기 때문에 로컬에서 임의로 제거 후 테스트 해봤는데 어색한 부분은 없었습니다 !!
- UserInfoCard, SearchBar 컴포넌트의 수정사항이 많지 않아서 해당 PR에서 같이 올리게 됐습니다 !
=> [#268] 메인, 로그인, 회원가입 페이지 레이아웃 및 UI 수정

src/components/common/BorderBox/BorderBox.style.ts, src/components/common/BorderBox/BorderBox.tsx, src/components/common/BorderBox/BorderBox.type.ts
isScaleActive props를 추가하여 hover시 scale여부를 별도로 지정할 수 있습니다.
디폴트 값은 false이며, scale 값을 1.01로 조절했습니다.
- isScaleActive를 분리하면서 기존에 scale되던 것들이 안 될 예정입니다. scale 효과 필요하시면 isScaleActive 속성 추가하여 사용하시면 됩니다!
=> [#274] BorderBox v1.1.0

src/components/common/Tooltip/ToolTip.tsx, src/components/common/Tooltip/index.ts
툴팁 컴포넌트를 추가하였습니다.
[kiwing_tooltip_1.0.0.webm](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/c77b92e8-d8e7-4919-98cb-3b92b8dbf1d4)
사용법이 약간 복잡? 합니다.
예시로 구조 설명을 드리자면 
아래 코드에서 툴팁을 포함한 전체 크기를 감지하고 있는 relative 속성을 가진 div로 묶어야합니다.
왜냐하면 툴팁은 이 크기를 기준으로 생성되기 때문입니다.
그 다음, 툴팁 컴포넌트로 실제 감싸고자 하는 코드를 감싸줍니다.
```tsx
<div style={{ position: 'relative' }}>
<Tooltip
$direction="bottom"
$options="hover"
$tooltip="툴팁"
$size={1.6}
$isArrow={false}
$textColor="black"
>
<Toggle
on={isShared}
onChange={handleToggle}
isBackgroundGray={true}
isContentShow={true}
width="7rem"
height="2.5rem"
fontSize="1.2rem"
style={{ marginTop: '0.5rem' }}
/>
</Tooltip>
</div>
```
이미지로 설명하자면 아래와 같은 느낌이네요.
뭔가,,, 더 깔끔한 방법으로 할 수도 있을 것 같은데 지금 당장은 어려울 것 같습니당,,
=> [#320] 툴팁 v1.0.0

src/App.tsx, src/components/Main/InfoUpdateModal/InfoUpdateModal.const.ts, src/components/Main/InfoUpdateModal/InfoUpdateModal.tsx, src/components/common/UserInfoCard/UserInfoCard.hook.tsx, src/components/common/UserInfoCard/UserInfoCard.tsx, src/pages/AuthPage/Auth.tsx, src/pages/MainPage/Main.tsx, src/pages/RegisterPage/Register.hook.ts, src/pages/RegisterPage/Register.tsx, src/routes/index.tsx, src/stores/index.ts
@SoJuSo @kim-hyunjoo @pkb9239
서비스 로그인 시 정보 입력을 안하고 뒤로가기 버튼을 눌렀을 때 MainPage에서 무한으로 Spinner 컴포넌트가 출력되는 문제를 해결했습니다.
문제가 되는 부분은 아래와 같았습니다.
- 서비스 로그인 후, 브라우저에 포커스를 주지 않은 상태에서 뒤로가기 버튼을 눌렀을 땐 `구글 로그인 -> /auth?access-token=~~ -> / -> (/ 에서 자동으로 넘어옴) /register`의 과정으로 되돌아오는 문제가 생기진 않았습니다.
- **서비스 로그인 후, 브라우저에 포커스를 준 상태 (화면 클릭 등)에서 뒤로가기 버튼을 눌렀을 땐 `/` 로 바로 넘어가져서** 무한으로 Spinner 컴포넌트가 출력됐습니다. (메인 페이지에선 닉네임이 없는 유저는 /register 페이지로 넘겨주는 과정에서 생기는 화면 깜빡임을 방지하기 위해 `리프레시 토큰이 존재하고 닉네임이 없다면 Spinner 컴포넌트를 출력`시켜주고 있습니다.)
MainPage에서 해당 문제를 처리해주기엔 AuthPage, RegisterPage, MainPage 세 군데에서 인증 관련 확인 및 처리를 해주게 되는 구조이기 때문에 MainPage에서는 저장된 유저 정보를 이용한 조건부 렌더링만 실시하도록 하고 AuthPage, RegisterPage에서만 인증 관련 확인 및 처리를 하는 것이 바람직하다고 생각하여 `RegisterPage`에서 뒤로가기 기능을 제한하는 방법을 채택했습니다.
- 다만 브라우저 정책 상 `브라우저에 포커스가 가지 않은 상태에선 popstate 이벤트가 …
=> [#305] 회원가입 과정 버그 hotfix

index.html, src/components/Layout/Layout.tsx, src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.style.ts, src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.tsx
- 아이폰 환경에서의 safeArea를 대응하였습니다.
- 안드로이드 환경에서 사용자가 하단 내비게이션 바 위치 중에 존재하는 경우 뒤로가기 시 앱이 종료되는 동작을 추가하였습니다.
- 하단 내비게이션 바 위치에 존재할 때 뒤로가기 버튼이 아닌 현재 위치를 보여주도록 변경하였습니다.
- safeArea 테스트 부탁드립니다. 아이폰 형님들,,, 다만 개별 코드로직에서 바꿀 필요는 없는 것으로 에뮬레이터 상에서는 확인했습니다!
- 안드로이드 일 경우 하단 내비게이션 바 path로 이동할 시 `window.history.pushState({ noBackExitsApp: true }, '');` 를 브라우저 히스토리에 push하여 바로 앱이 종료되도록 수정하였습니다.
=> [#303] PWA 환경에서 발생하는 아이폰, 안드로이드 디바이슈 에러 핸들링

src/components/common/QuestionCard/QuestionCard.tsx, src/components/common/QuestionCard/QuestionCard.type.tsx, src/pages/HubPage/Hub.tsx, src/pages/MainPage/Main.tsx
QuestionCard에서 bundle 목록을 불러오는 로직을 수정했습니다.
기존에는 각 카드마다 bundle 목록을 불러와서 비효율적인 네트워크 요청이 상당히 발생하였습니다.
이를 해결하기 위해 상단 페이지 단에서 한 번만 호출하고 해당 데이터를 내려주는 방식으로 변경하여 해결하였습니다.
해결 후에는 이제 한 번만 호출되는 것을 확인하실 수 있습니다.
@JaeHyunGround 제가 메인에도 로직 추가했습니다!
=> [#309] questionCard v1.1.1

src/components/SharedBundle/SharedBundleCard/SharedBundleCard.style.ts, src/pages/SharedItemPage/SharedItem.hook.ts, src/pages/SharedItemPage/SharedItem.tsx, src/types/index.ts
꾸머리 상세 api의 구조가 바뀜에 따라서 코드 로직을 변경하였습니다.
기존의 원래는 유저정보를 상세 api에서 writerId를 이용해서 유정정보를 가져왔다면 이제는 상세 조회만으로 writer 데이터를 이용해서 유저정보를 가져와 사용할수있게되었습니다.
- 디자인 피드백을 통해 공유된번들카드의 titlte 글씨 굵기를 500 => 450으로 수정하였습니다.
- 그리고 type/index.ts 에서 Bundle 타입을 수정하였습니다. 확인부탁드려요!
현재 로컬 서버에서 꾸러미 상세 페이지가 보이지않으므로 빠르게 코드리뷰 부탁드립니당 ! !
=> [#337] SharedItemPage v1.2.0

src/components/MyBundle/MyBundleDetail/MyBundleDetail.style.ts, src/components/MyBundle/MyBundleItem/MyBundleItem.style.ts, src/components/MyBundle/MyBundleList/MyBundleList.style.ts, src/components/MyBundle/MyBundleModal/MyBundleModal.const.tsx, src/components/MyBundle/MyQuestionModal/MyQuestionModal.const.tsx, src/components/common/QuestionBox/QuestionBox.style.ts, src/components/common/QuestionBox/QuestionBox.tsx
- MybundleItem font-weight: 400으로 변경했습니다.
- QuestionBox font-weight: 300으로 변경했습니다.
- 모바일에서 MyBundleItem 사이 gap을 줄였습니다.
- 그랩 아이콘 바깥으로 분리했습니다.
- 질문/꾸러미 최소 2글자 이상 입력하도록 validate를 추가했습니다.
- 이번엔 테스크 저번보다 많이 작습니다 ㅎㅎ 괜찮죠?
=> [#347] MyBundlePage v1.3.0

src/hooks/toast.tsx
Toast 컴포넌트를 수정했습니다.
- 모바일 환경에서 toast 알림이 화면 너비를 다 차지하는 문제를 해결했습니다.
- 화면 포커스를 잃어도 toast close 시간이 흐르도록 옵션을 수정했습니다.
- 모바일 환경에서는 progressBar를 숨겼고, 데스크톱 환경에서는 progressBar를 출력해줬습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/67a1923d-b24b-414c-ab55-d2208ed9dc84
- 자료를 더 찾아보고 `모바일 환경에서 알림이 쌓이는 구조`로 리펙토링 해보겠습니다 !!
=> [#359] Toast 컴포넌트  v1.0.1
