Team-kiwing/Team-3seco-kiwing-fe

src/App.tsx, src/main.tsx, src/pages/AuthPage/index.tsx, src/pages/HubPage/index.tsx, src/pages/MainPage/index.tsx, src/pages/MyListPage/index.tsx, src/pages/NotFoundPage/index.tsx, src/pages/RegisterPage/index.tsx, src/pages/ReportPage/index.tsx, src/pages/SharedItemPage/index.tsx, src/pages/SharedPage/index.tsx, src/pages/TestPage/index.tsx, src/pages/index.ts, src/routes/index.tsx
테스트페이지를 포함한 전체 페이지에 대한 기본 안내문구를 div태그로 추가하였습니다.
- 라우팅이 제대로 동작하지 않는 이슈를 인지, 해결하였습니다.
- 원인
기존의 코드에서 Router를 외부에서 처리해주는 로직이 없어 라우팅 처리가 제대로 되지 않았습니다.
- 해결
Main.tsx에서 사용되는 부분을 BrowserRouter로 감싸준 뒤 App.tsx에서 Router처리를 하도록 코드구조를 개선하였습니다.
- import 구문 최적화를 위해서 위 스크린샷 처럼 pages 하위에 index.ts 파일을 생성, export처리를 한번에 해주었습니다.
이렇게 처리할 경우, 개별 import구문 생성이 아닌 하나의 import 구문 내부에서 객체로 감싸서 여러 페이지를 가져올 수 있기에 import구문이 깔끔해져서 구조를 변경하였습니다.
- 개별 페이지에 안내문구를 추가해두었습니다.
감사합니다.
=> [#6] 프로젝트 세팅 v1.0.1

src/constants/index.ts, src/main.tsx, src/styles/theme.ts
브랜치 생성 중 모닝 이슈로 인해 잘못된 버전으로 브랜치 명칭을 작성하였습니다. 신경쓰도록 하겠습니다..
- tanstackQuery 전역 설정
- 전역 default theme 코드 추가
- 전역 constants 추가
=> [#26] 프로젝트 세팅 v1.1.0

src/utils/crypto.ts
AES 암복호화 코드를 추가하였습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/104a1c27-8a5f-4682-a433-875c1907ffbe
- 라이브러리를 활용해서 사용 코드 자체는 간단합니다.
- env 파일에 암호화 키를 지정해야 합니다. 해당 키는 화요일(2/13)에 슬랙 DM으로 개별 공유하도록 하겠습니다..!
=> [#10] AES 암,복호화 코드 v1.0.0

src/components/common/ImageUpload/ImageUpload.style.ts, src/components/common/ImageUpload/ImageUpload.tsx, src/components/common/ImageUpload/ImageUpload.type.ts, src/components/common/ImageUpload/index.tsx
ImageUpload 컴포넌트를 구현하였습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/81172451/5667245c-0953-4fab-ab6f-e973a5dacff1
- props는 onImageFileUrl, onImageFile가 있습니다.
- `...props` 를 주어서 확장할 수 있게 열어두었습니다.
- onImageFileUrl는 ImageUpload를 사용하는 곳으로 업로드한 파일의 url 값을 전달합니다. 이 url이 이제 previewImage를 구현할때 사용됩니다. 
- onImageFile는  ImageUpload를 사용하는 곳으로 업로드한 파일 자체를 전달합니다. 즉 실질적인 api 연동에 필요한 값을 전달합니다.
- 제가 생각한 것은 사용하는 곳에서 useState를 사용하여 사용하면 될거같습니다.
- 제가 처음 구현하는 부분이라 빠진거나 수정해야할 부분있으면 알려주시면 감사하겠습니다.
=> [#19] ImageUpload 컴포넌트 v1.0.0 

src/components/common/Avatar/Avatar.style.ts
Avatar 컴포넌트의 border 색상을 #d9d9d9에서 전역 테마 gray_100으로 수정했습니다.
코드가 한 줄 바뀐 거라 봐주실 코드는 많이 없어요 !!
=> [#32] Avatar 컴포넌트 v1.0.1

src/components/common/ShadowBox/ShadowBox.style.ts, src/components/common/ShadowBox/ShadowBox.tsx, src/components/common/ShadowBox/ShadowBox.type.ts
기존 px로만 적용할 수 있던 width, height 속성을 rem, %단위 등 다양한 단위로 사용될 수 있도록 변경합니다.
- 큰 내용은 없습니다!
=> [#35] ShadowBox 컴포넌트 v1.0.1

src/components/common/Avatar/Avatar.tsx
Avatar 컴포넌트의 jsDoc를 수정했습니다.
1줄만 수정해서 봐주실 코드는 많이 없습니다 !
=> [#46] Avatar 컴포넌트 jsDoc 수정 v1.0.2

src/constants/index.ts, src/constants/router.ts, src/routes/index.tsx, src/styles/globalStyles.ts
금일 코어 타임에 공통 작업한 [#60](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/issues/60) 코드입니다.
**작업 내역**
- 모바일 환경 대응 전역 웹킷 코드 추가
- 일부 스타일 관련 코드 상수화
- 라우팅 주소 코드 상수화
=> [#60] 프로젝트 세팅 v1.1.1

src/components/common/Selector/Selector.style.ts, src/components/common/Selector/Selector.tsx, src/components/common/Selector/Selector.type.ts, src/components/common/Selector/index.tsx
공통 컴포넌트인 Selector를 구현하였습니다.
```js
const [isRecent, setIsRecent] = useState<boolean>(true);
const [isAll, setIsAll] = useState<boolean>(true);
return (
<>
<div style={{ width: '200px' }}>
<Selector
isState={isRecent}
content={['최근순', '스크랩 순']}
onSelected={(item) => setIsRecent(item)}
/>
</div>
<div style={{ width: '200px' }}>
<Selector
isState={isAll}
size={2}
content={['전체 글 ', '내가 작성한 글']}
onSelected={(item) => setIsAll(item)}
/>
</div>
{isRecent ? <div>최신순 리스트</div> : <div>스크랩순 리스트</div>}
{isAll ? <div>전체 글</div> : <div>내가 작성한 글</div>}
</>
);
};
```
- `Selector` 컴포넌트는 필수 props는 `content`, `isState`, `onSelected` 입니다.
- `content`는 `string[]` 타입입니다. 필요한 text를 작성하여 넣어주시면 됩니다. ex)  content={['최근순', '스크랩 순']}
- `isState`는 `boolean` 타입입니다. true, false 값을 넣어주시면 됩니다. …
=> [#55] Selector 컴포넌트 구현 v1.0.0

src/components/MyListDropDown/MyListDropDown.tsx, src/components/MyListDropDown/index.ts, src/components/common/ShadowBox/ShadowBox.tsx, src/components/common/Toggle/Toggle.hook.ts, src/components/common/Toggle/Toggle.style.ts, src/components/common/Toggle/Toggle.tsx, src/components/common/Toggle/Toggle.type.ts, src/components/common/Toggle/index.ts
forwardRef를 이용하여 ref속성을 추가했습니다.
- DropDown의 useClickAway를 사용하기 위해 필요하기 때문에 빠르게 approve해주시면 감사하겠습니다.
- 별다른 내용은 없습니다!
=> [#72] ShadowBox v1.1.0

src/components/common/TagFilter/TagFilter.style.tsx, src/components/common/TagFilter/TagFilter.tsx, src/components/common/TagFilter/TagFilter.type.ts, src/components/common/TagFilter/index.tsx
공통 컴포넌트인 `TagFilter` 컴포넌트를  구현하였습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/81172451/ab99239a-b3c7-4341-9b46-7d22f630fd12
msw를 통해서 들어온 질문꾸러미를 만들어서 테스트 진행해보았습니다. (테스트할때 사용해보세요!)
dummy.json
```json
[
{
"id": 1,
"listName": "데브코스 면접리스트",
"tag": ["개발자", "백엔드", "프론트엔드"],
"subscribed": 5
},
{
"id": 2,
"listName": "삼성 면접리스트",
"tag": ["SW", "머신러닝", "프론트엔드"],
"subscribed": 2
},
{
"id": 3,
"listName": "구글 면접리스트",
"tag": ["개발자", "백엔드", "임베디드"],
"subscribed": 7
},
{
"id": 4,
"listName": "LG 면접리스트",
"tag": ["머신러닝", "SW", "프론트엔드"],
"subscribed": 5
},
{
"id": 5,
"listName": "카카오 면접리스트",
"tag": ["안드로이드", "백엔드", "프론트엔드"],
"subscribed": 5
},
{
"id": 6,
"listName": "쿠팡 면접리스트",
"tag": ["데이터", "백엔드", "프론트엔드"],
"subscribed": 1
}
]
```
handlers.ts
```ts
import { http, HttpResponse } from …
```
=> [#44] TagFilter 컴포넌트 구현 v1.0.0

src/constants/router.ts, src/pages/PolicyPage/Policy.tsx, src/pages/PolicyPage/index.tsx, src/pages/index.ts, src/routes/index.tsx, src/styles/theme.ts
금일 논의된 사항을 적용하였습니다. 
- border 색상을 정의합니다.
- 약관 페이지를 추가합니다.
theme.ts에 border_color가 각각 다크모드, 라이트모드에 추가되었습니다.
```ts
// 라이트 모드
border_color: '#D9D9D9',
// 다크 모드
border_color: '#5E5E5E',
```
=> [#80] 프로젝트 세팅 v1.1.2

src/components/common/DropDown/DropDown.tsx
기존에 normal모드일 때도 Footer 공간이 적용되는 현상이 있었는데, checkbox 모드일 때만 Footer 공간이 보이도록 수정하였습니다.
큰 내용 없어서 빠르게 approve 부탁드립니다!
=> [#85] DropDown v1.0.1

src/constants/index.ts, src/styles/globalStyles.ts, src/styles/theme.ts
금일 논의된 사항을 적용하였습니다.
- FONT_MEDIUM 정의
- BORDER_CARD_WEB, MOBILE 추가 및 BORDER 속성 rem단위로 교체
- theme.ts에 일관된 흰색, 검정색 색상 추가
- 스크롤 색상 border color로 변경하기
```tsx
// BORDER / 단위 rem //
export const BORDER_WEB = 1;
export const BORDER_MOBILE = 0.6;
export const BORDER_CARD_WEB = 1.5;
export const BORDER_CARD_MOBILE = 1.1;
// ... FONT 추가
export const FONT_MEDIUM = 500;
```
```tsx
// 스크롤 바 색상 수정
background-color: ${(props) => props.theme.border_color};
```
```tsx
// 스크롤 색상 border color로 변경하기
primary_white_text_color: '#e6e6e9',
primary_dark_text_color: '#0F1118',
```
=> [#102] 프로젝트 세팅 v1.1.3

src/components/common/Button/Button.style.ts, src/components/common/Button/Button.tsx, src/components/common/Button/Button.type.ts
- text color 디폴트 값을 primary_white_text_color로 적용했습니다.
- borderRadius props를 추가했습니다.
- 0.6rem보다 더 작아지지 않도록 방어코드를 추가했습니다.
- font-size, border-radius 값을 전역 상수 값으로 변경했습니다.
큰 작업 내용은 없습니다!
=> [#107] Button(사각형) v1.0.1

src/components/common/Toggle/Toggle.style.ts, src/components/common/Toggle/Toggle.tsx, src/components/common/Toggle/Toggle.type.ts
토글 컴포넌트의 border 적용 유무를 결정하는 isBorderShow props를 추가했습니다.
- 큰 내용은 없습니다!
=> [#105] Toggle v1.1.0

src/components/common/TagFilter/TagFilter.style.tsx, src/components/common/TagFilter/TagFilter.tsx
TagFilter 컴포넌트를 리펙토링하였습니다.
- `useResize`을 이용하여 모바일에 따른 뱃지 사이즈를 조정하였습니다.
-  전체적인 글자크기, 마진, 패딩값을 변경하였습니다.
```js
import { useState } from 'react';
import TagFilter from '@/components/common/TagFilter';
import { TagProps } from '@/components/common/TagFilter/TagFilter.type';
const [selectedTags, setSelectedTags] = useState<TagProps[]>([]);
const tagList = [
{ id: 1, name: '개발자' },
{ id: 2, name: '백엔드' },
{ id: 3, name: '서버' },
{ id: 4, name: '시스템' },
{ id: 5, name: '보안' },
{ id: 6, name: '프론트엔드' },
{ id: 7, name: '머신러닝' },
{ id: 8, name: 'QA' },
{ id: 9, name: '안드로이드' },
{ id: 10, name: '크로스플랫폼앱' },
{ id: 11, name: '데이터' },
{ id: 12, name: 'SW' },
{ id: 13, name: 'DevOps' },
{ id: 14, name: 'DBA' },
{ id: 15, name: '네트워크' },
{ id: 16, name: '웹퍼블리셔' },
{ id: 17, name: …
```
=> [#94] TagFilter 컴포넌트 리펙토링 v1.1.0

src/components/common/CircleButton/CircleButton.style.ts
font color default값 다크모드에서도 흰색으로 변경했습니다.
그외 누락된 type 적용하고 active, hover의 font color 적용을 제거했습니다.
큰 내용은 없습니다!
=> [#116] Button(원형) v.1.0.1

src/hooks/toast.tsx, src/routes/index.tsx
Toast 알림을 사용할 수 있는 hook을 구현했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/47d249ec-da34-4563-b80c-4acfcbe2bc32
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/8d4f1178-3037-4b47-adbe-4065cfec83e8
```typescript
import { notify } from '@/hooks/toast';
const toastDefault = () => {
notify({
type: 'default',
text: 'default 토스트 입니다.',
});
};
const toastSuccess = () => {
notify({
type: 'success',
text: 'success 토스트 입니다.',
});
};
const toastWarning = () => {
notify({
type: 'warning',
text: 'warning 토스트 입니다.',
});
};
const toastError = () => {
notify({
type: 'error',
text: 'error 토스트 입니다.',
});
};
return (
<>
<button
onClick={() => toastDefault()}
style={{
width: '20rem',
height: '20rem',
margin: '0.5rem',
backgroundColor: …
```
=> [#93] Toast 알림 구현 v1.0.0

src/components/common/Button/Button.tsx
- children props 추가
아주 간단한 코드 추가입니다!
=> [#136] Button v.1.1.0

src/components/common/CircleButton/CircleButton.style.ts, src/components/common/CircleButton/CircleButton.tsx
id 값은 그대로 투명한 Circle에만 부여됩니다. 대신 투명한 Circle이 일반 Circle 위에 오도록 구조를 변경했습니다.
그리고 children props를 추가했습니다.
큰 내용은 없습니다!
=> [#133] CircleButton v.1.1.0

src/components/common/Toggle/Toggle.style.ts, src/components/common/Toggle/Toggle.tsx, src/components/common/Toggle/Toggle.type.ts
- 어색한 css 개선
- fontSize props 추가
큰 내용은 없습니다!
=> [#143] Toggle v.1.2.0

src/components/Layout/Layout.tsx, src/components/Layout/index.tsx, src/routes/index.tsx
- 내비게이션 바 요소에 따른 레이아웃을 추가하였습니다.
[kiwing_GNB.webm](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/b3bc256b-2888-4b1e-8534-f7a09ade9709)
- 내비게이션 바를 전역에 적용하였습니다.
- 적용 후 내비게이션 바 조건에 따라서 레이아웃이 자동적으로 잡힙니다.
- 모든 코드는 css에서 처리하도록 구현하였습니다.
- 질문, 피드백 마음껏 부탁드립니다!
=> [#127] 레이아웃 v1.0.0

src/pages/NotFoundPage/NotFound.const.ts, src/pages/NotFoundPage/NotFound.style.ts, src/pages/NotFoundPage/NotFound.tsx
404 페이지의 일부 어색한 부분을 개선하고 코드를 리팩토링하였습니다.
- 어색한 css를 개선하였습니다.
- 텍스트 문구 상수화를 진행하였습니다.
특별한 내용은 없어유 ^-^
=> [#159] 404 페이지 v1.1.0

src/apis/axios.type.d.ts, src/apis/axiosErrorHandler.ts, src/apis/axiosInstance.ts, src/apis/axiosInterceptors.ts, src/constants/api.ts, src/services/auth.ts, src/services/bundles.ts, src/services/etc.ts, src/services/members.ts, src/services/questions.ts, src/stores/index.ts, src/types/index.ts
공통으로 전원 작업을 진행하였습니다.
API 인스턴스를 정의하였습니다.
API 호출 타입을 정의하였습니다.
API 호출 로직을 추가하였습니다.
다들 고생 많으셨어요!!
=> [#165] API 인스턴스 정의, 코드 추가 v1.0.0

src/components/common/ModalLayout/ModalLayout.style.ts, src/hooks/useModal.tsx
모달 css를 수정하였습니다.
- 다크모드에 대응하였습니다.
- borderRadius 값을 조절하였습니다.
간단한 css 사항 변경이 있습니다! 혹시 테스트해보시려면 아래 코드로 동작시키시면 됩니다.
<details>
<summary>테스트 코드 </summary>
```tsx
import { MobileTopNavBar } from '@/components/common/Navigator';
import { useModal } from '@/hooks/useModal';
import { ModalType } from '@/stores';
const Temp = () => {
const { modalState } = useModal();
return (
<>
<div>
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 kiwing 화이팅
kiwing 화이팅 kiwing 화이팅 kiwing 화이팅 …
```
=> [#157] 전역 상태 모달 v1.1.0

src/components/common/TagFilter/TagFilter.tsx, src/components/common/TagFilter/TagFilter.type.ts
태그 타입을 어제 선언한 api타입으로 변경하였습니다.
작업내용말고는 별다를게 없습니다.. 아마 번들카드나 다른것도 바꿔야할거같긴하네요  !
=> [#168] TagFilter의 tag타입 변경  v1.1.1

src/components/common/SearchBar/SearchBar.style.ts, src/components/common/SearchBar/SearchBar.tsx, src/components/common/SearchBar/SearchBar.type.ts
SearchBar 컴포넌트를 사용할 때 react-hook-form 의 register 함수가 target인 input 태그를 찾지 못하는 문제가 있었습니다.
[Textarea](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/pull/134), [Input](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/pull/139) 컴포넌트에서도 react-hook-form이 적용되지 않는 문제가 있었는데, 이는 컴포넌트를 사용하는 곳과 컴포넌트 간 뎁스가 1이어서 `ref를 부여`함으로써 register 함수가 타겟인 input or textarea 태그를 찾을 수 있었습니다.
하지만 SearchBar 컴포넌트의 경우 `사용하는 곳 - SearchBar - Input` 2뎁스를 가지기 때문에 기존 `ref를 부여하는 방법`으로는 해결할 수 없습니다. 따라서 `useFormContext / FormProvider` 을 사용하여 문제를 해결할 수 있었습니다. [참고한 링크](https://velog.io/@boyeon_jeong/React-Hook-Form-Controller-useController)
react-hook-form 관련 내용을 학습할 때 참고했던 [링크](https://tech.osci.kr/introduce-react-hook-form/)도 남깁니다 !
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/537450a6-1d7b-4566-8a2 …
=> [#145] SearchBar v2.0.0

src/pages/PolicyPage/Policy.style.ts, src/pages/PolicyPage/Policy.tsx
- 전역 레이아웃이 추가됨에 따라 nav바와 페이지 컨텐츠 간 간격을 부여했습니다.
- `이전 페이지로 돌아가기` 버튼에 word-break 옵션을 추가했습니다. (모바일 환경에서 보다 더 자연스럽게 보이기 위함입니다.)
간단한 레이아웃 수정 코드입니다 !
=> [#173] PolicyPage v1.1.0

src/components/common/EasterEgg/EasterEgg.const.ts, src/components/common/EasterEgg/EasterEgg.style.ts, src/components/common/EasterEgg/EasterEgg.tsx, src/components/common/EasterEgg/EasterEgg.type.ts
- 이스터에그 컴포넌트 리팩토링 및 버그수정입니다.
- styled 컴포넌트 에러가 뜨는 요소를 수정하였습니다.
- 컨벤션에 맞게 컴포넌트 구조를 리팩토링하였습니다.
=> [#178] EasterEgg v1.0.1

src/components/common/BorderBox/BorderBox.style.ts, src/components/common/BorderBox/BorderBox.tsx, src/components/common/BorderBox/BorderBox.type.ts, src/components/common/BorderBox/index.ts
ShadowBox와 호환되는 BorderBox 컴포넌트를 구현했습니다.
- border 0.15rem으로 주었는데 적절한가요?
=> [#181] BorderBox v1.0.0

src/constants/queryKeys.ts, src/hooks/useFetchTags.ts, src/pages/RegisterPage/Register.style.ts, src/pages/RegisterPage/Register.tsx, src/pages/RegisterPage/Register.type.ts, src/pages/RegisterPage/index.tsx
RegisterPage 레이아웃 작업을 진행했습니다.
- `useFetchTags` hook을 생성했습니다.
- 해당 hook은 api를 통해 태그 필터에 들어갈 태그 목록을 불러오는 hook입니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/4ca8c63d-c7b9-41bb-acbd-aa324af04885
=> 현재는 가입 버튼 눌렀을 때 알림 문구가 영상에서의 alert가 아닌 **toast 알림**으로 나옵니다 ! 또한 페이지의 `kiwing` 이라는 단어에 심볼 컬러를 부여했습니다 !!
- 규모가 커질 것을 대비하여 레이아웃 작업 PR을 먼저 올리고, `react-hook-form 적용 + API 연동` 작업은 버전업 해서 PR 올리겠습니다 :)
- 레이아웃, 디자인, 코드 구조에 문제가 없는지 선생님들의 평가가 필요합니다 !.!
=> [#121] RegisterPage v1.0.0

src/components/common/ModalLayout/ModalLayout.style.ts, src/utils/bodyScrollLock.ts
모달 관련 기능 버그 픽스 및 디자인 리팩토링을 진행하였습니다.
- bodyScrollLock 로직 재구성을 진행하였습니다.
기존에 스크롤이 없어도 모달 실행 시 padding값을 추가하여 레이아웃이 깨지는 이슈가 발생했고 
스크롤 유무를 구별하는 변수를 추가하여 해결했습니다.
- 간단한 디자인 수정도 진행하였습니다.
=> [#183] 전역 상태 모달 v1.1.1

src/components/MyBundle/MyBundleIndex/MyBundleIndex.style.ts, src/components/MyBundle/MyBundleIndex/MyBundleIndex.tsx, src/components/MyBundle/MyBundleIndex/MyBundleIndex.type.ts, src/components/MyBundle/MyBundleIndex/index.ts, src/components/common/QuestionBox/QuestionBox.style.ts
내 질문 꾸러미 관리 페이지의 웹 기준 오른쪽 하단에 위치한 MyBundleIndex 컴포넌트를 구현했습니다.
a태그를 이용하여 해당 위치로 이동시켜줄 수 있습니다.
사용하는 곳에서 같은 id(question.id)를 부여하면 위치가 연동됩니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/78135416/29f5741f-1084-4dc4-ab55-340779478f65
- 해당 작업은 아직 머지 대기중인 PR들과 연관성이 높아 테스트 UI는 대충 만들었습니다 ㅜㅜ
- a 태그가 3줄 이상일 시 말줄임표를 적용했는데, 그냥 다 보여주는 게 좋을까요?
- a 태그 사용하면 어쩔 수 없이 주소 뒤에 '#question.id' 가 붙더라구요 ㅠㅠ location.href 변경해보려고도 했는데 잘 안돼서.. 혹시 새로 고침 없이 주소만 조용히 바꿀 수 있는 방법 아시는 분 계실까요...?
<details>
<summary>Test</summary>
```jsx
import { useEffect, useState } from 'react';
import styled, { css, useTheme } from 'styled-components';
import BorderBox from '@/components/common/BorderBox';
import Button from '@/components/common/Button';
import MyBundleIndex from '@/components/MyBundle/MyBundleIndex';
// …
```
=> [#201] MyBundleIndex v1.0.0

src/components/MyBundle/MyQuestionModal/MyQuestionModal.const.tsx, src/components/MyBundle/MyQuestionModal/MyQuestionModal.hook.tsx, src/components/MyBundle/MyQuestionModal/MyQuestionModal.style.ts, src/components/MyBundle/MyQuestionModal/MyQuestionModal.tsx, src/components/MyBundle/MyQuestionModal/MyQuestionModal.type.ts, src/components/MyBundle/MyQuestionModal/index.ts
내 질문 꾸러미 관리 페이지에서 질문을 작성하고 편집할 수 있는 MyQuestionModal을 구현했습니다.
UI위주로 작업했으며 연동 과정은 추후에 이전 PR들이 전부 머지 되는대로 진행할 예정입니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/78135416/0a26c9a0-99dc-4b30-8501-8194e5a05720
- 연관되어있는 PR이 너무 많아서 이번에도 테스트 코드 제공은 어렵습니다 ㅜㅜ
- UI 위주로 봐주시고 피드백 부탁드립니다!
=> [#205] MyQuestionModal v1.0.0

src/components/common/CircleButton/CircleButton.style.ts, src/components/common/CircleButton/CircleButton.tsx
isBackgroundWhite=true일 때, 어색해진 css를 자연스럽게 수정했습니다.
디자인만 바꾼거라 큰 내용은 없습니다!
=> [#226] CircleButton v1.1.1

src/App.tsx, src/components/common/QuestionCard/QuestionCard.hook.tsx, src/stores/index.ts, vercel.json
- 로그인 API 성공 시 사용자 데이터를 전역 저장소에 추가하였습니다.
- 위 과정에서 발생한 일부 타입 오류(nickName -> nickname 통일)을 수정하였습니다.
- 배포시 발생하는 proxy, spa문제를 해결하기 위해 vercel.json 파일을 추가하였습니다.
=> [#228] api v1.1.1

src/components/common/QuestionBox/QuestionBox.style.ts
QuestionBox 가독성을 위한 간단한 작업을 했습니다.
가독성을 위하여 `line-height`, `word-break` 적용하였습니다.
더 추가할만한게 있으면 말씀해주세요 !
```js
import QuestionBox from '@/components/common/QuestionBox';
// 요기다가 하시면 됩니다
return (
<>
<QuestionBox
rightItem={<button />}
question="API란 무엇인가요? 키윙서비스란 무엇인가요?! 추천받습니다"
answer="키윙은 면접을 대비하기에 최고인 곳입니다. 다같이 키윙 서비스를 많이 이용해봅시다 키윙 파이팅 파이팅 영원하라 키윙 서비스는 신입 개발자나 전문가들이 IT 기업의 면접에 대비할 수 있도록 도와주는 온라인 플랫폼입니다. 이 서비스는 면접 질문, 프로그래밍 과제, 기술적인 질문에 대한 답변 및 피드백을 제공하여 사용자들이 면접에 대비할 수 있도록 지원합니다. 윙 서비스는 다양한 기업과 직무에 따른 면접 질문들을 제공합니다. 사용자는 이를 통해 자신이 준비해야 할 주요 질문들을 파악할 수 있습니다. 또한 각 질문에 대한 모범 답변과 함께 사용자가 작성한 답변을 제공하여 개선할 수 있도록 돕습니다. 기술적인 질문과 피드백: 사용자가 면접에서 받을 수 있는 기술적인 질문들을 모은 자료와 함께, 실시간으로 피드백을 제공합니다. 이를 통해 사용자는 자신의 기술적인 능력을 향상시키고, 부족한 부분을 보완할 수 있습니다.
커뮤니티 및 지원: 사용자들은 키윙 커뮤니티를 통해 다른 …
```
=> [#197] QuestionBox 컴포넌트 v1.1.0

src/components/common/Badge/Badge.style.ts, src/styles/theme.ts
뱃지스타일의 색상을 수정하였습니다.
- 전역테마에서 스크랩뱃지 색상을 변경하였습니다.
- 기본 뱃지 스타일의 배경색을 수정하였습니다.( 눈에 잘 안보여서 )
- padding 값을 변경하였습니다
- HOT 뱃지 스타일의 글자를 정중앙으로 만들어주었습니다.
=> [#163] Badge 컴포넌트 v1.2.3

src/components/common/Skeleton/Base.tsx, src/components/common/Skeleton/Circle.tsx, src/components/common/Skeleton/Paragraph.tsx
바뀐 내용은 별로 없습니다. borderRadius값을 px을 rem단위로 수정하였습니다.
@kim-hyunjoo 그때 해주신 말씀이 기억이 잘 안나는데 혹시 빠진부분이 있을까요?!
=> [#248] Skeleton 컴포넌트 구현 v1.1.0

src/components/Layout/Layout.tsx, src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.tsx, src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.tsx, src/components/common/Navigator/WebNavBar/WebNavBar.style.tsx, src/components/common/Navigator/WebNavBar/WebNavBar.tsx, src/constants/index.ts, src/routes/index.tsx
내비게이션 바를 리팩토링, 수정하였습니다.
- 기존에 모달을 뚫고 나오는 현상을 수정하였습니다(z-index변경)
- 웹 페이지에서 어색한 외곽선이 생기는 현상을 수정하였습니다.
- 내비게이션 바의 조건부 렌더링 조건을 추가하였습니다.
=> [#221] 내비게이션 바 v1.1.0

src/components/Main/InfoUpdateModal/InfoUpdateModal.const.ts, src/components/Main/InfoUpdateModal/InfoUpdateModal.hook.tsx, src/components/Main/InfoUpdateModal/InfoUpdateModal.style.ts, src/components/Main/InfoUpdateModal/InfoUpdateModal.tsx, src/components/Main/InfoUpdateModal/InfoUpdateModal.type.ts, src/components/Main/InfoUpdateModal/index.ts, src/components/common/UserInfoCard/UserInfoCard.hook.tsx, src/components/common/UserInfoCard/UserInfoCard.tsx, src/components/common/UserInfoCard/UserInfoCard.type.ts, src/services/members.ts
UserInfoCard의 기능을 추가했습니다.
- 오른쪽 아이콘(정보 수정, 로그아웃)을 눌렀을 때 기능을 추가했습니다.
UserInfoCard에서 디바운스 로직을 정의된 hook로 수정했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/9d094ead-20cb-499d-99b9-b49366260863
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/15659598-7c4c-4836-be6b-74567789f9fb
- API 신인 저희 팀원분들 덕분에 끝낼 수 있었습니다..ㅎㅎ
- 모달에서 정보 수정할 때 `본인 사용자 ID를 그대로 사용하려고 해도 중복 처리 되는 문제`가 있어 이 부분은 백엔드에 말씀드려놨으니, 백엔드에서 반영 해주시면 제대로 된 테스트를 할 수 있을 것 같습니다 !
=> [#65] UserInfoCard v1.1.0

src/components/common/Avatar/Avatar.const.ts, src/pages/MainPage/Main.style.ts
메인페이지 배너, 아바타 컴포넌트의 기본 프로필 이미지 파일 경로를 수정했습니다.
앞에 /public 를 제거하면 되는 건지 확인 한 번만 부탁 드리겠습니다 !
=> [#264] hotfix - 이미지 경로 수정 v1.0.0

src/components/MyBundle/MyBundleIndex/MyBundleIndex.tsx, src/components/MyBundle/MyBundleList/MyBundleList.style.ts, src/components/MyBundle/MyBundleMenu/MyBundleMenu.tsx, src/pages/MyBundlePage/MyBundle.style.ts, src/pages/MyBundlePage/MyBundle.tsx
팀 논의 후 레이아웃 규격에 맞도록 MyBundlePage 레이아웃을 수정했습니다.
- css만 변경되어 큰 내용 없습니다!
=> [#272] MyBundlePage 레이아웃 수정 v1.1.1

src/components/common/Spinner/Spinner.style.ts, src/components/common/UserInfoCard/UserInfoCard.hook.tsx, src/components/common/UserInfoCard/UserInfoCard.tsx, src/constants/queryKeys.ts, src/pages/MainPage/Main.tsx, src/services/auth.ts
UserInfoCard의 로그아웃 기능을 리팩토링했습니다.
- 로그아웃 버튼 클릭 시 로그아웃 API를 호출했습니다.
- API 호출 성공 시, `userDataStore`의  isLogin, accessToken, userData를 초기화 해줬습니다.
메인 페이지에서 로그인 한 상태에서 새로고침을 했을 경우, 비로그인일 때의 메인 페이지가 잠깐 뜨는 것을 방지하기 위한 코드를 추가했습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/97944429/19ba10f4-3be9-4eef-8bc9-efc189a9d2f4
> 메인 페이지에서 로그인 한 상태에서 새로고침을 했을 경우, 비로그인일 때의 메인 페이지가 잠깐 뜨는 것을 방지하기 위한 코드를 추가했습니다.
해당 PR 제목과 관련 없는 내용을 추가하여 죄송하단 말씀 드립니다 ㅠㅠ
임의로 방어 코드를 추가하긴 했지만, 정석인 방법대로 한 것인지에 대한 의문이 들어 `멘토님께 자문을 구한 뒤, 수정을 할 계획입니다 !!`
=> [#278] UserInfoCard v1.2.0

src/components/common/ShadowBox/ShadowBox.style.ts
scale을 1.01로 변경했습니다.
- 한줄짜리라 0.5초 리뷰 가능합니다..
=> [#275] ShadowBox v1.2.0

src/components/Main/InfoUpdateModal/InfoUpdateModal.hook.tsx, src/components/common/Navigator/Navigator.hook.ts, src/constants/router.ts, src/hooks/useModal.tsx, src/pages/MainPage/Main.tsx
=> [#290] 배포 전 공통 QA

src/pages/RegisterPage/Register.tsx
서비스 최초 로그인 시 `/register` 페이지로 가지 않는 버그를 긴급 수정했습니다.
- 최초 로그인 후, 닉네임을 입력 안하고 다른 페이지로 이동할 경우 `/register` 페이지로 이동합니다.
- 로그인을 안 했을 땐 `/register` 페이지에 접근한다면 가지지 않고 `/`으로 리다이렉트 됩니다.
- 로그인 + 닉네임이 있을 경우, `/register`에 접근하면 `/`으로 리다이렉트 됩니다.
=> [#295] hotfix - 회원가입 기능 수정

src/pages/AuthPage/Auth.style.ts, src/pages/AuthPage/Auth.tsx
AuthPage에서 로고와 소개글 간 gap 속성을 부여했습니다.
kiwing 소개글을 일부 수정했습니다.
바뀐 내용은 많이 없어요 !!
=> [#292] 페이지 - AuthPage v1.1.1

src/components/common/UserInfoCard/UserInfoCard.style.ts, src/components/common/UserInfoCard/UserInfoCard.tsx, src/pages/MainPage/Main.style.ts, src/pages/MainPage/Main.tsx
링크 미삽입 시 링크 아이콘이 찌그러지는 문제를 해결했습니다.
바뀐 코드는 많이 없습니다 !
- fit-content 속성을 제거해서 링크 영역이 `가장 긴 링크를 기준으로 영역이 잡힙니다.` 
링크 아이콘 문제를 해결하기 위해 어쩔 수 없이 제거를 헀습니다...! 좋은 솔루션이 있으면 공유 부탁드려요 !!
=> [#293] 공통 - UserInfoCard v1.2.1

src/components/MyBundle/MyBundleDetail/MyBundleDetail.tsx, src/components/MyBundle/MyBundleIndex/MyBundleIndex.style.ts, src/components/MyBundle/MyBundleList/MyBundleList.tsx, src/components/MyBundle/MyQuestionBox/MyQuestionBox.tsx, src/components/MyBundle/MyQuestionBox/PcRightItem/PcRightItem.tsx, src/components/common/QuestionBox/QuestionBox.style.ts, src/components/common/QuestionBox/QuestionBox.tsx, src/components/common/QuestionBox/QuestionBox.type.ts, src/components/common/Toggle/Toggle.style.ts, src/components/common/Toggle/Toggle.tsx, src/components/common/Toggle/Toggle.type.ts
QuestionBox에 새로운 기능 추가 및 기존 디자인 변경이 이루어졌습니다.
https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/78135416/e054129b-0a8a-4a1d-b2e6-5437b30c8b62
- active시 background color가 기존 심볼 색상에서 border_color로 변경되었습니다.
- 답변 더블클릭 시 notion처럼 답변 편집이 가능하도록 만들었습니다. 
- 원하는 내용으로 수정한 뒤 onBlur 이벤트가 발생하면 답변이 업데이트됩니다.
- 공유된 페이지에서 사용되는 QuestionBox에 문제가 생기지 않도록 분기처리를 했습니다.
- 문제 없는지 확인해주세요!
=> [#287] QuestionBox v1.2.0

src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.tsx, src/components/common/Navigator/WebNavBar/WebNavBar.tsx
=> [#300] 내비게이션 바 v1.1.1

src/pages/HubPage/Hub.style.ts, src/pages/HubPage/Hub.tsx, src/pages/NotFoundPage/NotFound.style.ts, src/pages/ReportPage/Report.style.ts
- 허브, 404, 문의 페이지 태그 수정을 진행하였습니다.
- 모바일 환경에서 QuestionCard의 최대 길이를 로그인 여부에 따라 구별하도록 수정하였습니다.
=> [#310] 허브, 404, 문의 페이지 태그 수정

src/components/SharedBundle/SharedBundleBox/SharedBundleBox.style.ts, src/components/SharedBundle/SharedBundleBox/SharedBundleBox.tsx, src/components/SharedBundle/SharedBundleCard/SharedBundleCard.style.ts, src/components/SharedBundle/SharedBundleCard/SharedBundleCard.tsx, src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.tsx, src/components/common/QuestionBox/QuestionBox.style.ts, src/components/common/QuestionBox/QuestionBox.tsx
SharedItemPage에 들어가는 컴포넌트들의 스타일링을 수정하였습니다.(꾸러미에 질문이 없을 때의 UI를 구현하였습니다.)
SharedItemPage에 들어가는 컴포넌트 중 몇개의 태그들을 수정하였습니다.
=> [#323] SharedItemPage v1.1.0

src/components/SharedBundle/SharedBundleCard/SharedBundleCard.style.ts, src/components/common/ShadowBox/ShadowBox.style.ts, src/pages/SharedItemPage/SharedItem.hook.ts, src/pages/SharedItemPage/SharedItem.tsx, src/types/index.ts
isActive시 color: white로 변경했습니다.
공유된 꾸러미 페이지에서 임의로 color 부여된 부분 삭제했습니다.
- 슬랙에도 올렸지만 공유된 꾸러미 페이지에서 아이콘도 같이 white로 변경하고, 사이즈도 s로 줄이는 것에 대해 같이 논의해보면 좋을 것 같아요~
=> [#344] ShadowBox v1.2.1

src/components/common/BorderBox/BorderBox.style.ts
isActive시 color: white로 변경했습니다.
- 단어 딱 하나 바뀌었습니다 ㅎㅎ
=> [#345] BorderBox v1.1.1

src/components/common/Button/Button.tsx
버튼 디폴트 색상 color: white로 변경했습니다.
- 한 줄 바뀌었습니다!
=> [#346] Button v1.1.1

src/components/common/Selector/Selector.style.ts, src/components/common/Selector/Selector.tsx
간단합니다. font-size의 기본값을 1.7에서 => 1.6으로 변경하였고 모바일에서는 1.4로 수정하였습니다.
빠르게 approve부탁드려용!
=> [#339] Selector 컴포넌트 v1.2.1

src/components/common/UserInfoCard/UserInfoCard.style.ts, src/constants/validation.ts, src/pages/MainPage/Main.style.ts, src/pages/MainPage/Main.tsx
메인 페이지에서 피드백 사항을 변경했습니다.
- UserInfoCard 사용자 ID에 @ 붙이기
- 최근 등록된 질문, 최근 등록된 꾸러미 텍스트 굵기 500으로 설정
- 최근 등록된 질문, 최근 등록된 꾸러미 사이 Divider 높이를 유동적으로 변하게 설정
- UserInfoCard에서 추가된 링크, 선택된 태그가 없을 때 출력되는 문구에 cursor: default 추가, 드래그 방지
- 사용자 정보 수정 모달에서 초기 사용자 ID인 `kiwing-31231-~~` 를 대처하기 위한 validation 수정
- 3/20일 까지 나온 피드백을 반영했습니다 !! 
- 제가 담당하고 있는 페이지 리팩토링은 #327 #328 에서 진행하겠습니다 !
=> [#338] MainPage v1.1.2 - 피드백 반영

src/apis/axiosInstance.ts, src/components/common/QuestionCard/QuestionCard.hook.tsx
=> [#368] 1.0.1 배포 핫픽스

src/apis/axiosInstance.ts, src/components/common/QuestionCard/QuestionCard.hook.tsx
* 🐛fix : 불필요한 에러 메세지 수정
* 🐛fix : 중복 쿼리키 변경
=> [#371] 1.0.1 배포 핫픽스
